server:
  port: ${PORT}

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET}

oauth2:
  front:
    client_id: ${OAUTH2_CLIENT_ID}
    client_secret: ${OAUTH2_CLIENT_SECRET}
  access_token_validity: ${OAUTH2_ACCESS_VALIDITY}
  refresh_token_validity: ${OAUTH2_REFRESH_VALIDITY}

springdoc:
  api-docs:
    path: /api-docs

logging:
  level:
    org.springframework.security: TRACE
    org.hibernate: ERROR